// Generate per-locale compact emoji datasets (`src/data/<locale>.gen.ts`)
// from `emojibase-data` (devDependency — the raw datasets never ship).
//
// The output is committed: `pnpm typecheck` / `pnpm build` must work from a
// fresh checkout without a pre-build generation step (the daisyui theme-css
// generator can emit into `dist/` because tsgo doesn't need its output; this
// one is tsgo *input*, so it lives in `src/`). Regenerate manually with
// `pnpm -F @sigx/lynx-emoji gen:data` after bumping emojibase-data or
// editing LOCALES, and commit the result. Deterministic for a given
// emojibase-data version.
//
// Each emitted module wraps the payload in `JSON.parse('…')` — a single
// string literal parses faster than an equivalent object literal in every
// JS engine, keeps tsgo from type-walking ~1900 object expressions, and
// shrinks the emitted .js.
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '../src/data');

/** Locales to generate — each becomes a `@sigx/lynx-emoji/data/<locale>` subpath export. */
const LOCALES = ['en'];

/** The CLDR "component" group (skin-tone swatches, hair styles) — not pickable emoji. */
const COMPONENT_GROUP = 2;

/** U+1F3FB–U+1F3FF modifier hexcodes, index = tone - 1. */
const TONE_HEX = ['1F3FB', '1F3FC', '1F3FD', '1F3FE', '1F3FF'];

/** messages.skinTones is keyed alphabetically; the picker wants tone order 1..5. */
const TONE_KEYS = ['light', 'medium-light', 'medium', 'medium-dark', 'dark'];

const { version } = require('emojibase-data/package.json');

for (const locale of LOCALES) {
    const compact = require(`emojibase-data/${locale}/compact.json`);
    const messages = require(`emojibase-data/${locale}/messages.json`);
    const shortcodes = require(`emojibase-data/${locale}/shortcodes/emojibase.json`);

    const groups = messages.groups
        .filter((g) => g.order !== COMPONENT_GROUP)
        .sort((a, b) => a.order - b.order);
    const categoryIndexByOrder = new Map(groups.map((g, i) => [g.order, i]));

    const emojis = [];
    for (const entry of compact) {
        const c = categoryIndexByOrder.get(entry.group);
        if (c === undefined) continue; // component group or ungrouped
        const datum = {
            e: entry.unicode,
            n: entry.label,
            c,
            o: entry.order ?? 0,
        };
        if (entry.tags?.length) datum.k = entry.tags;
        const sc = shortcodes[entry.hexcode];
        if (sc) datum.sc = Array.isArray(sc) ? sc : [sc];
        const skins = uniformSkins(entry.skins);
        if (skins) datum.s = skins;
        emojis.push(datum);
    }
    emojis.sort((a, b) => a.c - b.c || a.o - b.o);

    const data = {
        locale,
        categories: groups.map((g) => ({ key: g.key, label: g.message })),
        emojis,
        skinTones: TONE_KEYS.map(
            (key) => messages.skinTones.find((t) => t.key === key)?.message ?? key,
        ),
    };

    const json = JSON.stringify(data)
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'");
    const ts = `/* AUTO-GENERATED by scripts/gen-data.mjs from emojibase-data@${version} (locale: ${locale}) — do not edit.\n`
        + ` * Regenerate with \`pnpm -F @sigx/lynx-emoji gen:data\`. */\n`
        + `import type { EmojiData } from './schema.js';\n\n`
        + `export const data: EmojiData = JSON.parse(\n    '${json}',\n) as EmojiData;\n\n`
        + `export default data;\n`;

    mkdirSync(outDir, { recursive: true });
    const out = join(outDir, `${locale}.gen.ts`);
    writeFileSync(out, ts);
    console.log(
        `gen-data: ${locale} — ${emojis.length} emoji, ${data.categories.length} categories, `
        + `${emojis.filter((e) => e.s).length} with skin tones → ${out} (${(ts.length / 1024).toFixed(0)} KB)`,
    );
}

/**
 * Map an entry's skin variants to five uniform-tone glyphs (`[light…dark]`).
 * Tone is inferred from the modifier hexcodes in the variant's hexcode —
 * compact data has no `tone` field. Variants mixing two different tones
 * (couple/handshake combinations) are skipped; return null unless all five
 * uniform tones exist.
 */
function uniformSkins(skins) {
    if (!skins?.length) return null;
    const byTone = [null, null, null, null, null];
    for (const skin of skins) {
        const modifiers = skin.hexcode.split('-').filter((h) => TONE_HEX.includes(h));
        if (modifiers.length === 0) continue;
        const tone = TONE_HEX.indexOf(modifiers[0]);
        if (modifiers.some((m) => m !== modifiers[0])) continue; // mixed-tone variant
        byTone[tone] = skin.unicode;
    }
    return byTone.every(Boolean) ? byTone : null;
}
