/**
 * The pure half of the build — testable without touching the filesystem.
 * `build.mjs` feeds it the skin's lynx manifest; it returns the generated
 * TypeScript source for `src/generated/theme-data.ts`.
 */
import { formatHex } from 'culori';

/**
 * Bake one swatch to hex. The lynx manifest carries the design system's own
 * color spellings (oklch for daisyUI) — fine as registry metadata on the
 * web, but a lynx view cannot paint them, and the theme picker is exactly
 * where these values get painted. `formatHex` parses any CSS color culori
 * knows; an unparseable value is a build error, not a silent black swatch.
 */
export function bakeSwatch(swatch, themeName) {
    const baked = {};
    for (const [role, value] of Object.entries(swatch)) {
        const hex = formatHex(value);
        if (!hex) {
            throw new Error(
                `[lynx-daisyui-zero] theme "${themeName}" swatch role "${role}" has an `
                + `unparseable color ${JSON.stringify(value)} — cannot bake to hex`,
            );
        }
        baked[role] = hex;
    }
    return baked;
}

/**
 * Generate the theme-data module from the skin's lynx manifest.
 *
 * `expectedGrammarVersion` is the CLASS_GRAMMAR_VERSION of the INSTALLED
 * `@sigx/zero` contract — the envelope check: CSS emitted for a different
 * grammar would silently select nothing, so a mismatch fails the build.
 */
export function generateThemeData(manifest, expectedGrammarVersion) {
    if (manifest.target !== 'lynx') {
        throw new Error(`[lynx-daisyui-zero] expected a lynx-target manifest, got ${JSON.stringify(manifest.target)}`);
    }
    if (manifest.classGrammarVersion !== expectedGrammarVersion) {
        throw new Error(
            `[lynx-daisyui-zero] ${manifest.name}'s lynx CSS was emitted for class grammar `
            + `v${manifest.classGrammarVersion}, but the installed @sigx/zero contract is `
            + `v${expectedGrammarVersion} — align the @sigx/zero and @sigx/zero-daisyui catalog pins`,
        );
    }
    const themes = (manifest.themes ?? []).map((theme) => ({
        name: theme.name,
        colorScheme: theme.colorScheme,
        ...(theme.pair !== undefined ? { pair: theme.pair } : {}),
        swatch: bakeSwatch(theme.swatch ?? {}, theme.name),
    }));
    if (themes.length === 0) {
        throw new Error(`[lynx-daisyui-zero] ${manifest.name}'s lynx manifest declares no themes`);
    }
    // daisyUI declares no scalable --text-* ramp (verified against its lynx
    // tokens.css), so the ramp constant ships empty and fontScale re-emission
    // is a documented no-op for this skin. Generated from tokens if a future
    // skin version adds one.
    const ramp = {};
    // The manifest's per-component `defaults` are the runtime's only channel
    // for default axis values — this target emits no `:not()` default twins,
    // so lynx-zero stamps them as concrete classes (registerAxisDefaults).
    const axisDefaults = {};
    for (const [scope, entry] of Object.entries(manifest.components ?? {})) {
        const declared = entry?.defaults;
        if (!declared || Object.keys(declared).length === 0) continue;
        for (const [axis, value] of Object.entries(declared)) {
            if (typeof value !== 'string') {
                throw new Error(
                    `[lynx-daisyui-zero] "${scope}" declares a non-string default for axis "${axis}": ${JSON.stringify(value)}`,
                );
            }
            const offered = Array.isArray(entry[axis]) ? entry[axis] : entry.axes?.[axis];
            if (Array.isArray(offered) && !offered.includes(value)) {
                throw new Error(
                    `[lynx-daisyui-zero] "${scope}" defaults ${axis} to ${JSON.stringify(value)}, `
                    + `which is not among its declared ${axis} values`,
                );
            }
        }
        axisDefaults[scope] = declared;
    }
    return `// AUTO-GENERATED by build.mjs from ${manifest.name}@${manifest.zeroVersion ?? 'unknown'}
// (dist/lynx/manifest.json). Do not edit — regenerate with \`pnpm build\`.
import type { ThemeInfo } from '@sigx/lynx-zero';

export const DAISY_CLASS_GRAMMAR_VERSION = ${manifest.classGrammarVersion};

export const DAISY_THEMES: readonly ThemeInfo[] = ${JSON.stringify(themes, null, 4)};

/** The scalable text ramp, empty when the skin declares none. */
export const DAISY_TEXT_RAMP: Record<string, string> = ${JSON.stringify(ramp)};

/** Per-scope default axis values from the manifest's \`components.<scope>.defaults\`. */
export const DAISY_AXIS_DEFAULTS: Record<string, Record<string, string>> = ${JSON.stringify(axisDefaults, null, 4)};
`;
}
