import SwiftUI
import Lynx

@main
struct {{appNamePascal}}App: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        WindowGroup {
            ContentView(devUrl: Self.getDevUrl())
        }
    }

    /// Read dev URL from launch arguments (passed by CLI via simctl). On warm
    /// restart (icon tap with no launch args), fall back to the URL persisted
    /// by `LynxContainerView` so HMR can reconnect without rerunning the CLI.
    static func getDevUrl() -> String? {
        let args = ProcessInfo.processInfo.arguments
        if let index = args.firstIndex(of: "--sigx_dev_url"), index + 1 < args.count {
            return args[index + 1]
        }
        #if DEBUG
        return SigxDevClient.lastConnectedUrl
        #else
        return nil
        #endif
    }
}

/// AppDelegate plumbing — every UIApplicationDelegate callback delegates
/// into `GeneratedAppDelegateHooks` (auto-generated by `sigx-lynx prebuild`
/// from each `@sigx/lynx-*` package's `sigx-module.json`). Adding a new
/// package with AppDelegate-level hooks is a one-package change — no edit
/// here required.
class AppDelegate: NSObject, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
    ) -> Bool {
        // 1. Initialize the Lynx config (dev mode picks DevTemplateProvider so
        //    HTTP loading works against the dev server).
        #if DEBUG
        let devUrl = {{appNamePascal}}App.getDevUrl()
        if devUrl != nil {
            SigxDevClient.registerServices()
            LynxSetupService.shared.initialize(provider: DevTemplateProvider())
            SigxDevClient.enableDevMode()
        } else {
            LynxSetupService.shared.initialize()
        }
        #else
        LynxSetupService.shared.initialize()
        #endif

        // 2. Register native modules the auto-linker discovered.
        if let config = LynxSetupService.shared.config {
            GeneratedModuleRegistry.registerAll(on: config)
        } else {
            print("[App] Warning: LynxConfig not available, skipping module registration")
        }

        // 3. Fan out didFinishLaunching to every registered package hook.
        GeneratedAppDelegateHooks.didFinishLaunching(application, launchOptions: launchOptions)
        return true
    }

    // Warm-start custom-scheme deep links (myapp://...).
    func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    ) -> Bool {
        return GeneratedAppDelegateHooks.openURL(url, options: options)
    }

    // Universal Links (https://your.domain/...) when associated domains are configured.
    func application(
        _ application: UIApplication,
        continue userActivity: NSUserActivity,
        restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
    ) -> Bool {
        GeneratedAppDelegateHooks.continueUserActivity(userActivity)
        return true
    }
}
