import Foundation
import Lynx

/**
 * Auto-generated module registry.
 * Generated by `sigx prebuild` — do not edit manually.
 *
 * This stub keeps `App.swift` compiling before the first prebuild. Once
 * prebuild runs, this file is overwritten with real registrations.
 */
class GeneratedModuleRegistry {
    static func registerAll(on config: LynxConfig) {
        print("[GeneratedModuleRegistry] No auto-linked modules")
    }
}
