package {{packageName}}

import android.content.Context
import android.util.Log

/**
 * Auto-generated module registry.
 * Generated by `sigx prebuild` — do not edit manually.
 */
object GeneratedModuleRegistry {

    private const val TAG = "GeneratedModuleRegistry"

    fun registerAll(context: Context) {
        Log.i(TAG, "No auto-linked modules")
    }
}
