package {{packageName}}

import com.lynx.tasm.LynxView

/**
 * Auto-generated lifecycle-publisher attachment point.
 * Generated by `sigx prebuild` — do not edit manually.
 *
 * This stub keeps `MainActivity.kt` compiling before the first prebuild.
 * Once prebuild runs with lifecycle-kind manifests, this file is overwritten
 * with real `attachAll` content.
 */
object GeneratedLifecyclePublishers {
    fun attachAll(lynxView: LynxView): List<Any> {
        return emptyList()
    }
}
