package {{packageName}}

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.ViewGroup
import androidx.activity.compose.setContent
import androidx.fragment.app.FragmentActivity
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.viewinterop.AndroidView
import com.lynx.tasm.LynxBooleanOption
import com.lynx.tasm.LynxView
import com.lynx.tasm.LynxViewBuilder
import com.lynx.tasm.TemplateData
import com.lynx.xelement.XElementBehaviors

/**
 * Host Activity for the sigx-lynx app.
 *
 * Lifecycle plumbing is intentionally minimal: each callback delegates into
 * `GeneratedActivityHooks` (auto-generated by `sigx prebuild` from each
 * `@sigx/lynx-*` package's `signalx-module.json`). Adding a new package with
 * Activity-level hooks is a one-package change — no edit needed here.
 *
 * Extends [FragmentActivity] (a [androidx.activity.ComponentActivity]
 * subclass, so Compose/activity-result keep working) because androidx
 * prompts like `BiometricPrompt` require a FragmentActivity host — see
 * `SigxActivityHolder.currentFragmentActivity()` in `@sigx/lynx-core`.
 */
class MainActivity : FragmentActivity() {

    companion object {
        /** Intent extra key for dev server bundle URL */
        const val EXTRA_DEV_URL = "sigx_dev_url"
    }

    // ── Lifecycle delegation ───────────────────────────────────────────────
    // Every callback here forwards into the auto-generated dispatcher.
    // Don't add reflective package-specific calls — declare an
    // `activityHook` in the package's `signalx-module.json` instead and the
    // generator will wire it.

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.Theme_SigxApp)
        super.onCreate(savedInstanceState)
        GeneratedActivityHooks.onCreate(this, savedInstanceState)

        // Treat an empty string the same as missing — the CLI's no-JS-dev
        // path passes `--es sigx_dev_url ""` for sandbox apps so MainActivity
        // can still launch via adb without baking a real URL.
        val intentDevUrl = intent.getStringExtra(EXTRA_DEV_URL)?.takeIf { it.isNotEmpty() }
        // On warm restart (icon tap), the launcher intent has no extras. Fall back to
        // the last URL we saw so HMR can reconnect without rerunning `sigx dev`.
        val persistedDevUrl = if (intentDevUrl == null && BuildConfig.DEBUG) {
            com.sigx.devclient.DevSettings(this).lastConnectedUrl.takeIf { it.isNotEmpty() }
        } else null
        val devUrl = intentDevUrl ?: persistedDevUrl
        // Detect whether a non-empty `main.lynx.bundle` is baked into the
        // APK. If not (and no dev URL), fall through to DevHomeScreen so the
        // app doesn't crash trying to render a missing/empty asset. That's
        // the path Go-style sandbox apps take on cold launch.
        val hasBakedBundle = runCatching {
            assets.open("main.lynx.bundle").use { it.available() > 0 }
        }.getOrDefault(false)
        // Startup bundle resolver — a linked OTA package (e.g.
        // @sigx/lynx-updates) can redirect startup to a downloaded bundle.
        // Never consulted in dev-URL runs (the dev server owns the bundle),
        // and the resolver mutates rollback state, so resolve exactly once
        // here — not inside a composable.
        // The readability re-check guards the resolver-to-load gap (and any
        // misbehaving resolver): an unreadable path must fall through to the
        // baked-bundle / sandbox gating below, not white-screen production.
        val otaBundlePath = if (devUrl == null) {
            GeneratedBundleResolver.resolveStartupBundlePath(this)
                ?.takeIf { java.io.File(it).isFile }
        } else null

        when {
            intentDevUrl != null -> Log.d("SigxDevClient", "Dev mode: loading bundle from $devUrl (intent)")
            persistedDevUrl != null -> Log.d("SigxDevClient", "Dev mode: loading bundle from $devUrl (persisted)")
            otaBundlePath != null -> Log.d("SigxDevClient", "Production mode: loading OTA bundle from $otaBundlePath")
            hasBakedBundle -> Log.d("SigxDevClient", "Production mode: loading bundle from assets")
            else -> Log.d("SigxDevClient", "Sandbox mode: no URL and no bundle — DevHomeScreen")
        }

        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    var currentUrl by remember { mutableStateOf(devUrl) }

                    when {
                        currentUrl != null && BuildConfig.DEBUG -> {
                            com.sigx.devclient.DevLynxScreen(
                                url = currentUrl!!,
                                onBack = {
                                    if (hasBakedBundle) finish() else currentUrl = null
                                },
                                onLynxViewBuilder = { builder ->
                                    GeneratedBehaviors.attachAll(builder)
                                },
                                onLynxViewCreated = { lynxView ->
                                    GeneratedLifecyclePublishers.attachAll(lynxView)
                                },
                            )
                        }
                        otaBundlePath != null -> {
                            ProductionLynxScreen(bundleName = "main.lynx.bundle", bundleFilePath = otaBundlePath)
                        }
                        hasBakedBundle -> {
                            ProductionLynxScreen(bundleName = "main.lynx.bundle")
                        }
                        BuildConfig.DEBUG -> {
                            com.sigx.devclient.DevHomeScreen(
                                onSelectUrl = { currentUrl = it },
                            )
                        }
                        else -> {
                            Text(
                                text = "No bundle found",
                                modifier = Modifier.fillMaxSize(),
                            )
                        }
                    }
                }
            }
        }
    }

    override fun onResume() {
        super.onResume()
        GeneratedActivityHooks.onResume(this)
    }

    override fun onPause() {
        super.onPause()
        GeneratedActivityHooks.onPause(this)
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        GeneratedActivityHooks.onNewIntent(this, intent)
    }

    @Deprecated("Hook authors: implement onBackPressed in your ActivityHook instead")
    override fun onBackPressed() {
        if (GeneratedActivityHooks.onBackPressed(this)) return
        @Suppress("DEPRECATION")
        super.onBackPressed()
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<String>,
        grantResults: IntArray,
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        GeneratedActivityHooks.onRequestPermissionsResult(this, requestCode, permissions, grantResults)
    }

    // Dev-only hardware-keyboard reload. Pressing `R` on the host keyboard
    // when an Android emulator (or a Chromebook / DeX session) has focus
    // triggers an in-place LynxView reload. We dispatch to super first so
    // any focused text editor (including Compose `TextField`s, which focus
    // an `AndroidComposeView`, not an `EditText`) gets the keystroke, and
    // only reload when the event was unhandled AND no text editor is
    // currently composing.
    override fun dispatchKeyEvent(event: android.view.KeyEvent): Boolean {
        val handled = super.dispatchKeyEvent(event)
        if (handled) return true
        if (BuildConfig.DEBUG &&
            event.action == android.view.KeyEvent.ACTION_UP &&
            event.keyCode == android.view.KeyEvent.KEYCODE_R &&
            currentFocus?.onCheckIsTextEditor() != true
        ) {
            com.sigx.devclient.SigxDevClient.triggerRemoteReload()
            return true
        }
        return false
    }
}

@Composable
fun ProductionLynxScreen(bundleName: String, bundleFilePath: String? = null) {
    var loading by remember { mutableStateOf(true) }
    var error by remember { mutableStateOf<String?>(null) }

    Box(modifier = Modifier.fillMaxSize()) {
        AndroidView(
            modifier = Modifier.fillMaxSize(),
            factory = { ctx ->
                try {
                    val viewBuilder = LynxViewBuilder()
                    // Built-in Lynx behaviors carry `<list>` / `<list-item>` /
                    // `<list-container>` (and view/text/image/scroll-view).
                    // Register them explicitly so `<list>` resolves at runtime
                    // (issue #120) rather than relying on implicit registration.
                    viewBuilder.addBehaviors(com.lynx.tasm.behavior.BuiltInBehavior().create())
                    viewBuilder.addBehaviors(XElementBehaviors().create())
                    GeneratedBehaviors.attachAll(viewBuilder)

                    // Serve dynamic-import chunks from embedded assets (#599).
                    // Mirrors the dev-mode fetchers, which read from the dev
                    // server instead.
                    viewBuilder.setTemplateResourceFetcher(ProductionTemplateResourceFetcher(ctx))
                    viewBuilder.setEnableGenericResourceFetcher(LynxBooleanOption.TRUE)
                    viewBuilder.setGenericResourceFetcher(ProductionGenericResourceFetcher(ctx))
                    // An OTA update directory may carry its own async chunks in
                    // the future — search it before the baked assets.
                    SigxEmbeddedAssets.extraRoots =
                        bundleFilePath?.let { java.io.File(it).parentFile?.let(::listOf) } ?: emptyList()

                    val lynxView = viewBuilder.build(ctx)
                    lynxView.layoutParams = ViewGroup.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                    )

                    GeneratedLifecyclePublishers.attachAll(lynxView)

                    // OTA path (resolved by GeneratedBundleResolver) wins over
                    // the baked asset; fall back to the asset if the file
                    // vanished between resolution and load.
                    val bundle = bundleFilePath
                        ?.let { path -> runCatching { java.io.File(path).readBytes() }.getOrNull() }
                        ?: ctx.assets.open(bundleName).readBytes()
                    lynxView.renderTemplateWithBaseUrl(
                        bundle,
                        TemplateData.empty(),
                        bundleFilePath?.let { "file://$it" } ?: ""
                    )

                    loading = false
                    lynxView
                } catch (e: Exception) {
                    error = e.message ?: "Failed to create LynxView"
                    loading = false
                    android.view.View(ctx)
                }
            }
        )

        if (loading) {
            CircularProgressIndicator(
                modifier = Modifier.align(Alignment.Center)
            )
        }

        if (error != null) {
            Text(
                text = "Error: $error",
                color = MaterialTheme.colorScheme.error,
                modifier = Modifier.align(Alignment.Center)
            )
        }
    }
}
