package {{packageName}}

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.ViewGroup
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.viewinterop.AndroidView
import com.lynx.tasm.LynxView
import com.lynx.tasm.LynxViewBuilder
import com.lynx.tasm.TemplateData
import com.lynx.xelement.XElementBehaviors

/**
 * Host Activity for the sigx-lynx app.
 *
 * Lifecycle plumbing is intentionally minimal: each callback delegates into
 * `GeneratedActivityHooks` (auto-generated by `sigx prebuild` from each
 * `@sigx/lynx-*` package's `signalx-module.json`). Adding a new package with
 * Activity-level hooks is a one-package change — no edit needed here.
 */
class MainActivity : ComponentActivity() {

    companion object {
        /** Intent extra key for dev server bundle URL */
        const val EXTRA_DEV_URL = "sigx_dev_url"
    }

    // ── Lifecycle delegation ───────────────────────────────────────────────
    // Every callback here forwards into the auto-generated dispatcher.
    // Don't add reflective package-specific calls — declare an
    // `activityHook` in the package's `signalx-module.json` instead and the
    // generator will wire it.

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.Theme_SigxApp)
        super.onCreate(savedInstanceState)
        GeneratedActivityHooks.onCreate(this, savedInstanceState)

        // Treat an empty string the same as missing — the CLI's no-JS-dev
        // path passes `--es sigx_dev_url ""` for sandbox apps so MainActivity
        // can still launch via adb without baking a real URL.
        val intentDevUrl = intent.getStringExtra(EXTRA_DEV_URL)?.takeIf { it.isNotEmpty() }
        // On warm restart (icon tap), the launcher intent has no extras. Fall back to
        // the last URL we saw so HMR can reconnect without rerunning `sigx dev`.
        val persistedDevUrl = if (intentDevUrl == null && BuildConfig.DEBUG) {
            com.sigx.devclient.DevSettings(this).lastConnectedUrl.takeIf { it.isNotEmpty() }
        } else null
        val devUrl = intentDevUrl ?: persistedDevUrl
        // Detect whether a non-empty `main.lynx.bundle` is baked into the
        // APK. If not (and no dev URL), fall through to DevHomeScreen so the
        // app doesn't crash trying to render a missing/empty asset. That's
        // the path Go-style sandbox apps take on cold launch.
        val hasBakedBundle = runCatching {
            assets.open("main.lynx.bundle").use { it.available() > 0 }
        }.getOrDefault(false)

        when {
            intentDevUrl != null -> Log.d("SigxDevClient", "Dev mode: loading bundle from $devUrl (intent)")
            persistedDevUrl != null -> Log.d("SigxDevClient", "Dev mode: loading bundle from $devUrl (persisted)")
            hasBakedBundle -> Log.d("SigxDevClient", "Production mode: loading bundle from assets")
            else -> Log.d("SigxDevClient", "Sandbox mode: no URL and no bundle — DevHomeScreen")
        }

        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    var currentUrl by remember { mutableStateOf(devUrl) }

                    when {
                        currentUrl != null && BuildConfig.DEBUG -> {
                            com.sigx.devclient.DevLynxScreen(
                                url = currentUrl!!,
                                onBack = {
                                    if (hasBakedBundle) finish() else currentUrl = null
                                },
                                onLynxViewCreated = { lynxView ->
                                    GeneratedLifecyclePublishers.attachAll(lynxView)
                                },
                            )
                        }
                        hasBakedBundle -> {
                            ProductionLynxScreen(bundleName = "main.lynx.bundle")
                        }
                        BuildConfig.DEBUG -> {
                            com.sigx.devclient.DevHomeScreen(
                                onSelectUrl = { currentUrl = it },
                            )
                        }
                        else -> {
                            Text(
                                text = "No bundle found",
                                modifier = Modifier.fillMaxSize(),
                            )
                        }
                    }
                }
            }
        }
    }

    override fun onResume() {
        super.onResume()
        GeneratedActivityHooks.onResume(this)
    }

    override fun onPause() {
        super.onPause()
        GeneratedActivityHooks.onPause(this)
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        GeneratedActivityHooks.onNewIntent(this, intent)
    }

    @Deprecated("Hook authors: implement onBackPressed in your ActivityHook instead")
    override fun onBackPressed() {
        if (GeneratedActivityHooks.onBackPressed(this)) return
        @Suppress("DEPRECATION")
        super.onBackPressed()
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<String>,
        grantResults: IntArray,
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        GeneratedActivityHooks.onRequestPermissionsResult(this, requestCode, permissions, grantResults)
    }
}

@Composable
fun ProductionLynxScreen(bundleName: String) {
    var loading by remember { mutableStateOf(true) }
    var error by remember { mutableStateOf<String?>(null) }

    Box(modifier = Modifier.fillMaxSize()) {
        AndroidView(
            modifier = Modifier.fillMaxSize(),
            factory = { ctx ->
                try {
                    val viewBuilder = LynxViewBuilder()
                    viewBuilder.addBehaviors(XElementBehaviors().create())

                    val lynxView = viewBuilder.build(ctx)
                    lynxView.layoutParams = ViewGroup.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                    )

                    GeneratedLifecyclePublishers.attachAll(lynxView)

                    val bundle = ctx.assets.open(bundleName).readBytes()
                    lynxView.renderTemplateWithBaseUrl(bundle, TemplateData.empty(), "")

                    loading = false
                    lynxView
                } catch (e: Exception) {
                    error = e.message ?: "Failed to create LynxView"
                    loading = false
                    android.view.View(ctx)
                }
            }
        )

        if (loading) {
            CircularProgressIndicator(
                modifier = Modifier.align(Alignment.Center)
            )
        }

        if (error != null) {
            Text(
                text = "Error: $error",
                color = MaterialTheme.colorScheme.error,
                modifier = Modifier.align(Alignment.Center)
            )
        }
    }
}
